### ISSUE TITLE
[WANT] 나를 구독한 사람 조회, 내가 구독한 사람 조회 반환값 추가

### ISSUE THREAD

**Issue by sw-devr** [screeningHumanity/TMT-BE-MemberMypage#7]
## 요청 구분
- [x] 신규 요구 사항 발생
- [ ] 수정 요청

## 요청 내용
나를 구독한 사람 조회, 내가 구독한 사람 조회 API에서 
해당 유저의 자산 랭킹도 함께 반환 부탁드립니다 !
![image](https://github.com/screeningHumanity/TMT-BE-MemberMypage/assets/141290308/249f68d6-02cc-4500-94b5-158b674d6aec)

**Comment by KangBaekGwa** [comment]
확인했습니다.

**Comment by KangBaekGwa** [comment]
{
  "httpStatus": "OK",
  "isSuccess": true,
  "message": "요청 응답 성공",
  "code": 200,
  "data": [
    {
      "id": 1,
      "nickName": "테스트1"
    },
    {
      "id": 2,
      "nickName": "테스트2"
    },
    {
      "id": 3,
      "nickName": "테스트3"
    },
    {
      "id": 4,
      "nickName": "테스트4"
    }
  ]
}

**Comment by KangBaekGwa** [comment]
이런식으로 업데이트 예정입니다~
